<!DOCTYPE html> 
<html> 
    <head> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, maximum-scale=1.0" />

        <title>Assignment 4</title> 

        <link href="style.css" media="screen" rel="stylesheet" type="text/css" />

    </head> 
    <body> 

        <div class="header">
            <p>
                <a href="index.html">Back to home</a>
            </p>

            <h1>Cindy Feng's Assignment 4</h1>
            <p>
                This assignment was completed in the MILL on 05/01/2019.
            </p>
            <p>
                <img src="Assignment4/Frontview.jpg" width=600></a>
            </p>
            <p>
                <b>Links to files used:</b>
                <ul>
                    <li><a href="https://cad.onshape.com/documents/b20f27ffd3082ac8732dba2d/w/12f09f66c36cde707af7fb69/e/4a96792c6f0e7a43d79cdc3d">Onshape CAD model</a>
                    <li><a href="Assignment4/PropellerBlades.stl">Propeller stl</a></li>
                    <li><a href="Assignment4/KeychainHolder.stl">Keychain Holder stl</a></li>
                </ul>
            </p>
            <h2>Modeling in Onshape</h2>
            <p>
                Having never used Onshape before, I started with YouTube tutorials to learn the basics.  I used this video to learn how to model a propeller: <a href="https://www.youtube.com/watch?v=JSPJQyVPAko">https://www.youtube.com/watch?v=JSPJQyVPAko</a>, and modified it for number of blades and depth of propeller.  Given my mechanical engineering background and my current role in which I use CATIA everyday, I picked up Onshape super quickly.  I made the blades 2 mm thick and filleted it to the cylinder body with a 4 mm fillet.  The hole cut into the middle of the propeller is diameter 3 mm.
            </p>
            <p>
                <img src="Assignment4/Onshape_singleblade.jpg" width=300></a>
            </p>
            <p>
                <img src="Assignment4/Onshape_blades.jpg" width=300></a>
            </p>
            <p>
                I then improvised and modeled a holder for the fan.  I was originally intending it to be a keychain holder, but the final part was a little too thick to attach a keychain.  I ended with filleting all the edges, so there would be no sharp inner edges, where I was scared about the fan possibly cracking when I removed support material.  The hole in the center is also diameter 3 mm.  I did not have a pin yet, but I figured I wanted a 3 mm pin in the center.
            </p>
            <p>
                <img src="Assignment4/Onshape_backview.jpg" width=500></a>
            </p>
            <p>
                At the end I organized the tree into folders, and I renamed the parts so it made sense.  Not knowing what pin I would use as a fastener between the two pieces, I modeled a generic pin with a hexagonal cutout for an allen wrench.
            </p>
            <p>
                <img src="Assignment4/Onshape_folders.jpg" width=500></a>
            </p>
            <p>
                <img src="Assignment4/Onshape_pin.jpg" width=300></a>
            </p>
            <p>
                I then created the assembly and animated it!
            </p>
            <p>
                <img src ="Assignment4/Onshape_assembly.jpg" width=500></a>
            </p>
            <p>
                <img src="Assignment4/OnshapeAnimation.gif" width=600></a>
            </p>

<h2>3D Printing</h2>

            <p>
                I exported the propeller and keychain holder as stl files.  I imported the propeller stil into Dremel, generated support material everywhere, and previewed the layers.  I used higher infill because the part was so thin.
            </p>
            <p>
                Machine Settings: 
                <ul>
                    <li>Nozzle Temperature: 130 degrees C</li>
                    <li>Platform Temperature: 35 degrees C</li>
                    <li>Print Speed: 100%</li>
                    <li>35% infill</li>
                </ul>
            </p>
            <p>
                <img src="Assignment4/Dremel_layers_preview.gif" width=300></a>
            </p>
            <p>
                For the keychain holder, here are the print settings:
            </p>
            <p>
                <img src="Assignment4/Dremel_keychain_machine_settings.jpg" width=500></a>
            </p>
            <p>
                I then loaded these two gcode files into separate Dremels, and went to class for 2 hours, crossing my fingers that nothing would fail!  When I came back during break time, to my surprise/delight, the prints were both successful!
            </p>
            <p>
                <img src="Assignment4/Dremel_keychain_printed.jpg" width=500></a>
            </p>
            <p>
                <img src="Assignment4/Dremel_propeller_printed.jpg" width=500></a>
            </p>

<h2>The Final Product</h2>

            <p>
                While in class during Josh's lecture, I learned that I could purchase screws from him! Knowing that my holes were 3 mm diameter, I opted for the 2 mm shoulder screw and associated heat set insert.
            </p>
            <p>
                The most challenging part of this assignment was getting the support material off the propeller blades! I was so worried that I would break one of the blades off, but after an hour of trying to delicately cut the support material off with very little progress, I learned that the 2 mm thick blades with the 4 mm fillets were actually pretty hard to break off compared to the support meterial, and eventually I got all the support material off, except for a little bit around the hole, which made it so that extra thickness meant the screw was too short for the assembly.
            </p>
            <p>
                <img src="Assignment4/Propeller_support_material.jpg" width=500></a>
            </p>
            <p>
                Not having access to a soldering gun, I just got a hammer and press-fit the heat set insert into the back of the keychain holder.
            </p>
            <p>
                <img src="Assignment4/Hammer_keychain_holder.jpg" width=500></a>
            </p>
            <p>
                Given the extra thickness from the support material that I could not scratch off, I used an exacto knife to "countersink" around the hole so that the shoulder screw would sit deeper into the hole.  I was then able to screw into the heat set insert in the back!
            </p>
            <p>
                <img src="Assignment4/Propeller_blade_countersink.jpg" width=500></a>
            </p>
            <p>
                And here is the final product!
            </p>
            <p>
                <img src="Assignment4/Frontview.jpg" width=500></a>
            </p>
            <p>
                <img src="Assignment4/Backview.jpg" width=500></a>
            </p>
            <p> 
                And some gifs to show how it works!  They appear to spin backwards because of the gif frame rate.
            </p>
            <p>
                <img src="Assignment4/spin.gif" width=500></a>
            </p>
            <p>
                <img src="Assignment4/spin_blow.gif" width=500></a>
            </p>
            <p>
                Acknowledgements: Josh for the screws!
            </p>
        </div>
        
    </body>
</html>
